# -*- coding: utf-8 -*-
"""Resume_Matcher_Notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rJth8a3FGdBqV0td_YDc5UnBAQI-IBBt

## __Step 1: Extracting Text from Resume (PDF)__

We are doing this because-

NLP models don’t understand PDFs — they understand text
"""

# install required library
! pip install pymupdf

# Create a Simple File
import fitz         # PyMuPDF

def read_resume(pdf_file_name):
    text = ""

    pdf = fitz.open(pdf_file_name)

    for page in pdf:
        text = text + page.get_text()

    pdf.close()

    return text

resume_text = read_resume('/content/vanshika CV.pdf')
print(resume_text[:500])

"""## __Step 2: Text Cleaning__"""

import re

def clean_text(text):
    text = text.lower()                          # make everything lowercase
    text = re.sub(r'\s+', ' ', text)             # remove extra spaces and newlines
    text = re.sub(r'[^a-zA-Z0-9 ]', '', text)    # remove special characters
    return text.strip()

# cleaning the resume content
cleaned_resume_text = clean_text(resume_text)
print(cleaned_resume_text[:500])

"""## __Step 3: Understanding Text Meaning__"""

# load required library if not in system
!pip install sentence-transformers

# Load the Embedding Model
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

"""## __Step 4: Create Job Description Text__"""

job_description = """
We are looking for a Data Science Intern with strong skills in
Python, SQL, Machine Learning, NLP, and data analysis.
Experience with pandas and scikit-learn is a plus.
"""

# Generate Embeddings
resume_embedding = model.encode(cleaned_resume_text)
jd_embedding = model.encode(job_description)

"""## __Step 5: Measure Similarity__"""

from sklearn.metrics.pairwise import cosine_similarity

similarity_score = cosine_similarity(
    [resume_embedding],
    [jd_embedding]
)

print(similarity_score)

# converting to percentage
match_percentage = similarity_score[0][0] * 100
print(f"Resume Match Score: {match_percentage:.2f}%")

"""## __Step 6: Skill Extraction & Missing Skill Analysis__

__Step 6.1: Create a Skill List__
"""

skills_list = [
    "python", "sql", "machine learning", "deep learning",
    "nlp", "data analysis", "pandas", "numpy",
    "scikit-learn", "tensorflow", "pytorch",
    "excel", "power bi", "tableau"
]

"""__Step 6.2: Extract Skills from Text__"""

def extract_skills(text, skills):
    found_skills = []

    for skill in skills:
        if skill in text:
            found_skills.append(skill)

    return found_skills

"""__Step 6.3: Extract Resume & Job description Skills__"""

resume_skills = extract_skills(cleaned_resume_text, skills_list)
jd_skills = extract_skills(job_description.lower(), skills_list)

print("Skills in Resume:", resume_skills)
print("Skills in Job Description:", jd_skills)

"""__Step 6.4: Find Missing Skills__"""

missing_skills = list(set(jd_skills) - set(resume_skills))
print("Missing Skills:", missing_skills)

"""## __Step 7: Making Results Human-Friendly (Interpretation Layer)__

__Step 7.1: Interpret the Match Score__
"""

# score interpretation function
def interpret_score(score):
    if score >= 75:
        return "Strong Match"
    elif score >= 50:
        return "Moderate Match"
    else:
        return "Low Match"

"""__Step 7.2: Display a Clean Final Output__"""

print("=== *RESUME MATCH ANALYSIS* ===\n")

print(f"Match Score: {match_percentage:.2f}%")
print("Match Level:", interpret_score(match_percentage))

print("\nSkills Found in Resume:")
print(", ".join(resume_skills) if resume_skills else "None")

print("\nSkills Required in Job Description:")
print(", ".join(jd_skills) if jd_skills else "None")

print("\nMissing Skills:")
print(", ".join(missing_skills) if missing_skills else "None")

"""## __Step 8: Improving my model__

__Step 8.1: Creating  Skill Categories__
"""

matching_skills = list(set(resume_skills) & set(jd_skills))
missing_skills = list(set(jd_skills) - set(resume_skills))
extra_skills = list(set(resume_skills) - set(jd_skills))

"""__Step 8.2: Displaying extra skills__"""

print("=== SKILL GAP ANALYSIS ===\n")

print("Matching Skills:")
print(", ".join(matching_skills) if matching_skills else "None")

print("\nMissing Skills (Important to Learn):")
print(", ".join(missing_skills) if missing_skills else "None")

print("\nExtra Skills (Nice to Have):")
print(", ".join(extra_skills) if extra_skills else "None")

"""__Step 8.3: Resume Improvement Suggestions__"""

# creating suggestion function
def generate_suggestions(match_score, missing_skills):
    suggestions = []

    if match_score < 75:
        suggestions.append("Consider adding projects or experience relevant to the job description.")

    if missing_skills:
        suggestions.append("Add or highlight these skills in your resume: " + ", ".join(missing_skills))

    if match_score < 50:
        suggestions.append("Consider improving sections like Education or Work Experience for clarity and detail.")

    return suggestions

# apply the function
suggestions = generate_suggestions(match_percentage, missing_skills)

print("=== RESUME IMPROVEMENT SUGGESTIONS ===")
for idx, s in enumerate(suggestions, 1):
    print(f"{idx}. {s}")

